stages:          # List of stages for jobs, and their order of execution
  - build
  - test

# Build VSlib on change of relevant files
fgc4_vslib_build:
  stage: build
  timeout: 30 minutes

  image: registry.cern.ch/doaromin_test/fgc4-ci:latest
  variables:
    GIT_STRATEGY: clone
  script:
    - export PATH=/opt/fgcd2/bin/arm-gnu-toolchain-12.3.rel1-x86_64-aarch64-none-elf/bin:/opt/fgcd2/bin/arm-gnu-toolchain-12.3.rel1-x86_64-aarch64-none-linux-gnu/bin:$PATH
    - cd $CI_PROJECT_DIR/source/vslib
    - cmake -B build-vslib
        -DCMAKE_C_COMPILER=aarch64-none-elf-gcc
        -DCMAKE_CXX_COMPILER=aarch64-none-elf-g++
        -DCMAKE_SIZE=aarch64-none-elf-size
        -DCMAKE_BUILD_TYPE=Release
        -DLIBRARIES_HOME=/opt/fgcd2/libs
    - cmake --build build-vslib

  artifacts:
    paths:
      - $CI_PROJECT_DIR/source/vslib/build-vslib
    when: always
    expire_in: 1 months

  rules:
    - changes:
      - source

fgc4_vslib_docs:
  stage: build
  needs: [fgc4_vslib_build]
  timeout: 30 minutes

  image: registry.cern.ch/doaromin_test/fgc4-ci:latest
  variables:
    GIT_STRATEGY: clone
  script:
    - export PATH=/opt/fgcd2/bin/arm-gnu-toolchain-12.3.rel1-x86_64-aarch64-none-elf/bin:/opt/fgcd2/bin/arm-gnu-toolchain-12.3.rel1-x86_64-aarch64-none-linux-gnu/bin:$PATH
    - cd $CI_PROJECT_DIR/sw/fgc/fgc4/source/vslib/
    - doxygen docs/Doxyfile
    - cd docs/source/figures
    - bash convert_all_to_png.sh
    - cd ../..
    - make html

  artifacts:
    paths:
      - $CI_PROJECT_DIR/source/vslib/docs/doxygen
      - $CI_PROJECT_DIR/source/vslib/docs/build
    when: always
    expire_in: 1 month

  rules:
    - changes:
      - source

# Build and run FGC4 tests on change of files
fgc4_tests:
  stage: test
  needs: [fgc4_vslib_build]
  timeout: 30 minutes

  image: registry.cern.ch/doaromin_test/fgc4-ci:latest
  variables:
    GIT_STRATEGY: clone

  script:
    - export PATH=/opt/fgcd2/bin/arm-gnu-toolchain-12.3.rel1-x86_64-aarch64-none-linux-gnu/bin:$PATH

    # Workflow for building tests to be run on hardware
    - cd $CI_PROJECT_DIR/source/utils
    - cmake -B build-utils -G Ninja
        -DCMAKE_CXX_COMPILER=aarch64-none-linux-gnu-g++
        -DCMAKE_BUILD_TYPE=RelWithDebugInfo
        -DLIBRARIES_HOME=/opt/fgcd2/libs
    - cmake --build build-utils

    - cd $CI_PROJECT_DIR/source/vslib
    - cmake -B build-vslib-tests -G Ninja
        -DCMAKE_CXX_COMPILER=aarch64-none-linux-gnu-g++
        -DBUILD_TESTS=ON
        -DLIBRARIES_HOME=/opt/fgcd2/libs
        -DBMBOOT_INCLUDE=$PWD/../bmboot/include
    - cmake --build build-vslib-tests

    # Building and running tests within CI/CD
    # Utility module
    - cd $CI_PROJECT_DIR/source/utils
    - cmake -B build-utils-ci -G Ninja
        -DCMAKE_BUILD_TYPE=RelWithDebugInfo
        -DLIBRARIES_HOME=/opt/fgcd2/libs
    - cmake --build build-utils-ci
    - cd build-utils-ci
    - ./utilsTests

    # VSlib modules
    - cd $CI_PROJECT_DIR/source/vslib
    - cmake -B build-vslib-tests-ci -G Ninja
        -DBUILD_TESTS=ON
        -DLIBRARIES_HOME=/opt/fgcd2/libs
        -DBMBOOT_INCLUDE=$PWD/../bmboot/include
    - cmake --build build-vslib-tests-ci
    - cd build-vslib-tests-ci
    - ./background/backgroundTests
    - ./components/componentTests
    - ./parameters/parameterTests
    - ./utils/utilsTests

  artifacts:
    paths:
      - $CI_PROJECT_DIR/source/utils/build-utils
      - $CI_PROJECT_DIR/source/vslib/build-vslib-tests
    when: always
    expire_in: 1 month

  rules:
    - changes:
      - source
