repos:

  # Run fast code improvement/checks before running PR specific helpers.
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
        exclude: .patch$|^(source/hal/|source/bsp/|source/bmboot/)
      - id: check-added-large-files
        args: ['--maxkb=4096']
      - id: check-xml
      - id: check-yaml
        args: [--allow-multiple-documents]

  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v15.0.7
    hooks:
      - id: clang-format
        exclude: ^(lib)

  - repo: https://gitlab.com/daverona/pre-commit/cpp
    rev: 0.8.0                 # use the most recent version
    hooks:
    # Hooks using native
      - id: cppcheck             # static analyzer for C/C++ code